org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties
minecraft_version=[VERSIONED]
minecraft_version_range=[1.19.2,]
forge_version=[VERSIONED]
forge_version_range=[43,)

mapping_channel=parchment
mapping_version=[VERSIONED]

## Mod Properties
mod_id=tt20
mod_name=TT20
mod_license=AGPL-3.0
mod_version=0.7.1
mod_group_id=net.snackbag.tt20
mod_authors=JX_Snack, Lemonnik
mod_description=TT20 helps reduce lag by optimizing how ticks work when the server's TPS is low.

## Mod Dependencies
shitlib_version=1.2.3